# -*- mode: org; fill-column: 78; -*-
# Time-stamp: <2026-09-08 11:50:17 krylon>
#
#+TAGS: internals(i) ui(u) bug(b) feature(f)
#+TAGS: database(d) design(e), meditation(m)
#+TAGS: optimize(o) refactor(r) cleanup(c)
#+TODO: TODO(t)  RESEARCH(r) IMPLEMENT(i) TEST(e) | DONE(d) FAILED(f) CANCELLED(c)
#+TODO: MEDITATE(m) PLANNING(p) | SUSPENDED(s)
#+PRIORITIES: A G D

* Jazz [0/0]
  :PROPERTIES:
  :COOKIE_DATA: todo recursive
  :VISIBILITY: all
  :END:
** Clocktable
   #+BEGIN: clocktable :scope file :maxlevel 255 :emphasize t
   #+CAPTION: Clock summary at [2026-09-08 Di 11:50]
   | Headline                                    | Time    |         |      |      |
   |---------------------------------------------+---------+---------+------+------|
   | *Total time*                                | *16:57* |         |      |      |
   |---------------------------------------------+---------+---------+------+------|
   | *Jazz [0/0]*                                | *16:57* |         |      |      |
   | \_  /Components [0/0]/                      |         | /16:57/ |      |      |
   | \_    Model [0/0]                           |         |         | 0:39 |      |
   | \_    Database [0/0]                        |         |         | 6:20 |      |
   | \_    Job Entry [0/0]                       |         |         | 9:00 |      |
   | \_      Shell                               |         |         |      | 1:09 |
   | \_      Lua FTW!                            |         |         |      | 1:42 |
   | \_    Monitor [0/0]                         |         |         | 0:36 |      |
   | \_    Main/Common [0/1]                     |         |         | 0:22 |      |
   | \_      Supress logging to terminal when... |         |         |      | 0:22 |
   #+END:
** Components [0/0]
   :PROPERTIES:
   :COOKIE_DATA: todo recursive
   :VISIBILITY: all
   :END:
*** Model [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
    :LOGBOOK:
    CLOCK: [2026-09-01 Di 18:34]--[2026-09-01 Di 19:13] =>  0:39
    :END:
*** Database [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
    :LOGBOOK:
    CLOCK: [2026-09-02 Mi 10:56]--[2026-09-02 Mi 13:33] =>  2:37
    CLOCK: [2026-09-01 Di 19:13]--[2026-09-01 Di 22:56] =>  3:43
    :END:
    I think I might want to not use SQLite this time. Or do I?
    I definitely do need some kind of support for persistence. I /could/ use a
    kv-store, that should probably suffice for this project.
*** Job Entry [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
    :LOGBOOK:
    CLOCK: [2026-09-07 Mo 11:25]--[2026-09-07 Mo 12:20] =>  0:55
    CLOCK: [2026-09-07 Mo 11:20]--[2026-09-07 Mo 11:24] =>  0:04
    CLOCK: [2026-09-05 Sa 11:29]--[2026-09-05 Sa 13:01] =>  1:32
    CLOCK: [2026-09-04 Fr 10:23]--[2026-09-04 Fr 14:01] =>  3:38
    :END:
**** Shell
     :LOGBOOK:
     CLOCK: [2026-09-08 Di 10:07]--[2026-09-08 Di 11:16] =>  1:09
     :END:
**** Lua FTW!
     :LOGBOOK:
     CLOCK: [2026-09-07 Mo 11:16]--[2026-09-07 Mo 11:18] =>  0:02
     CLOCK: [2026-09-07 Mo 11:04]--[2026-09-07 Mo 11:12] =>  0:08
     CLOCK: [2026-09-07 Mo 10:15]--[2026-09-07 Mo 10:58] =>  0:43
     CLOCK: [2026-09-05 Sa 16:56]--[2026-09-05 Sa 17:45] =>  0:49
     :END:
     I think the entire idea is nonsense. I am not going to write a Lua script
     each time I want to run a Job.
     The interface should probably be more like at of at(1) where I just enter
     a sequence of commands.
*** Monitor [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
    :LOGBOOK:
    CLOCK: [2026-09-04 Fr 10:23]--[2026-09-04 Fr 10:23] =>  0:00
    CLOCK: [2026-09-03 Do 12:54]--[2026-09-03 Do 13:30] =>  0:36
    :END:
*** Main/Common [0/1]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
**** TODO Supress logging to terminal when Shell is running
     :LOGBOOK:
     CLOCK: [2026-09-08 Di 11:28]--[2026-09-08 Di 11:50] =>  0:22
     :END:
** Features [0/0]
   :PROPERTIES:
   :COOKIE_DATA: todo recursive
   :VISIBILITY: all
   :END:
*** JCL
**** Lua FTW?
     Okay, hear me out - Lua? I hadn't thought of that until just now, but
     there is a port of Lua 5.1 to Go. That would solve a bunch of problems at
     once.
     It appears gopher-lua is slightly more active.
     https://github.com/yuin/gopher-lua
     https://github.com/Shopify/go-lua
*** Submitting Jobs [0/0]
    The name "Jazz" is a play on the JES2/JES3 _Job Entry Systems_ on IBM
    z/OS. I mention this because I want to allow for some flexibility
    regarding the way I submit jobs to the queue.
    But I only have some very vague ideas right now.
    I definitely want a CLI interface like ts. But I also want to support a
    kind of JCL for multi-step jobs.
    Last but not least, submitting jobs via a web interface over a network
    connection would be cool (but low-priority at this point).
*** Multi-step jobs [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
    I want a job to not be just a single command, but - at least optionally -
    a sequence of commands that can be linked - loosely - like commands in
    shell, e.g. =cmdA && cmdB || cmdC=
**** Resumable jobs
     Also, I want to be able to suspend a job between steps and resume it
     later.
*** Parallel execution [0/0]
    It would be nice if I could define for steps within a job to be run in
    parallel. But that will add a lot of complexity, so I'm keeping that for
    later.
** Bugs [0/0]
